# Generated by Django 3.1 on 2020-08-22 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatar_id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar_name', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=14)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('avatar_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.avatar')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.profilestatus')),
            ],
        ),
    ]
